In [1]:
import pandas as pd

In [2]:
#importer le fichier Buchanan
dfDicoBuch = pd.read_csv("./../data/dictionary/1757_Buchanan-J.csv", delimiter=";", encoding="utf8")
dfDicoBuch.sample(n=5)

       nbSyll          pron origin warning remarques POS  lineId  pageId
2689        4  conjĕʹctŭral    NaN     NaN       NaN  a.    68.0      56
373         2      aʹlt_a_r    NaN     NaN       NaN  n.    51.0      24
5511        2       găʹrble     F.     NaN       NaN  v.    30.0      96
6941        4    inĕʹbrĭāte     L.     NaN       NaN  v.    62.0     117
13428       3     sŭrvīʹvor    NaN     NaN       NaN  n.    29.0     208

In [3]:
#importer le fichier PronChar
PronChar = pd.read_csv("./../data/dictionary/Buchanan_PronChar_counts.csv", delimiter=";", encoding="utf8")
PronChar.sample(n=50)

   char    occ graph
37    ˘     36   NaN
11    n   8612     n
62    ë      2     e
20    ĕ   4262     e
29    ū   1321     u
38    k    717     k
9     i   3783     i
5     u   1623     u
50    ė     83     e
8     t   8790     t
66    ó      1     o
34    ŭ   2085     u
67    ;      3   NaN
26    ī   1002     i
3     ă   4533     a
17    _   4124   NaN
53    (     28   NaN
35    ē    493     e
28    l   6260     l
31    g   2604     g
14    d   3758     d
70    х      2     x
52          57
4     c   5500     c
13    ā   2079     a
2     b   2288     b
15    o   3838     o
1     ʹ  12725   NaN
49    ȳ     43     y
71    р      1     p
61    à      4     a
23    v   1477     v
48    у      3     y
54    )     28   NaN
64    ô      4     o
44    z    214     z
72    ï      1     i
42    ̆    132     o
0     a   3207     a
33    ̇    266     o
45    -     31     -
6     s   2935     s
12    e   8952     e
18    m   3639     m
69    I      1     l
7     f   1809     f
16    ŏ   2797     o
41    ẇ     96     w
30    p   3775     p
19    h   2383     h

In [4]:
PronChar.fillna('', inplace=True)

In [5]:
PronChar.sample(n=50)

   char    occ graph
60    â      5     a
58    í      2     i
64    ô      4     o
69    I      1     l
50    ė     83     e
12    e   8952     e
25    ō    542     o
65    D      1     d
57    г      1     r
24    ĭ   5281     i
42    ̆    132     o
34    ŭ   2085     u
0     a   3207     a
35    ē    493     e
62    ë      2     e
41    ẇ     96     w
39    q    270     q
51    ȧ     54     a
16    ŏ   2797     o
68    á      1     a
20    ĕ   4262     e
1     ʹ  12725
36    w    796     w
67    ;      3
7     f   1809     f
56    а      2     a
66    ó      1     o
5     u   1623     u
54    )     28
10    ſ   4329     s
46    è     73     e
70    х      2     x
31    g   2604     g
59    ˙      3
33    ̇    266     o
22    r   9245     r
32    ȯ    371     o
27    j    251     j
28    l   6260     l
63    .     22
13    ā   2079     a
8     t   8790     t
30    p   3775     p
9     i   3783     i
23    v   1477     v
21    y   1952     y
61    à      4     a
3     ă   4533     a
26    ī   1002     i
11    n   8612     n

In [6]:
# a modifier (les noms des variables et fonctions)
def sampa2ipa(strSampa, dfMapping):
    ipaRes = ""
    
    for valSampa in strSampa:
        #print(valSampa)
        dfRowFinded = dfMapping[dfMapping['char']==valSampa]

        if len(dfRowFinded==1):
            ipaRes+=dfRowFinded.iloc[0]['graph']
        else:
            ipaRes+='?'
    return ipaRes

In [7]:
#dfDicoBuch['motVedette'] = dfDicoBuch.apply(lambda x: sampa2ipa(x['graph'], PronChar),1)

In [8]:
dfDicoBuch['motVedette'] = dfDicoBuch.apply(lambda x: sampa2ipa(x['pron'], PronChar),1)

In [9]:
dfDicoBuch['motVedette']

0           abacus
1            abaft
2        abaisance
3          abandon
4        abandoned
           ...
15795    zoography
15796    zoophytes
15797    zoophoric
15798    zootomist
15799       zotica
Name: motVedette, Length: 15800, dtype: object

In [10]:
dfDicoBuch.sample(n=10)

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette
11771,2,rīmy,NaN,nbSyll>1 et pas d'accent tonic,NaN,a.,26.0,185,rimy
14117,1,treeks,NaN,NaN,NaN,n.,2.0,218,treeks
14329,2,tȳʹrănt,NaN,NaN,NaN,n.,70.0,220,tyrant
6432,1,jăm_b_,NaN,NaN,NaN,n.,19.0,110,jamb
4580,2,ĕʹrror,L.,NaN,NaN,n.,28.0,83,error
4525,3,ĕʹpĭʹſtle,G.,NaN,NaN,n.,44.0,82,epistle
623,2,ăppeaʹſe,F.,NaN,NaN,v.,13.0,28,appease
7784,2,lĕʹſſ_e_n,NaN,NaN,NaN,v.,50.0,129,lessen
8909,2,mŭʹſlin,F.,NaN,NaN,n.,26.0,145,muslin
7682,1,lāve,F.,NaN,NaN,v.,20.0,128,lave

In [11]:
#importer le fichier BigiRichSample
BigiRichSample=pd.read_csv("./../data/dataframe/BigiRichSample.csv", delimiter=";", encoding="utf8")

In [12]:
BigiRichSample.sample(n=5)

                  hwd                 pronSampa           ipa
628             sholl                     S A l           ʃɑl
687          viewers'               v j u 3:r z       vjuɜ:rz
453  acquaintanceship  @ k w eI n t @ n s S i p  əkw?ntənsʃip
261            resale              r\ i: s eI l        ɹiːs?l
399            barbed                b A r\ b d         bɑɹbd

In [13]:
#jointure des deux tables
datej= pd.merge(dfDicoBuch, BigiRichSample, left_on='motVedette', right_on='hwd',how='left')

In [14]:
datej.sample(20)

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette,hwd,pronSampa,ipa
2959,2,c_o_ŭʹntry,F.,NaN,NaN,n.,52.0,60,country,NaN,NaN,NaN
15312,2,ŭʹrchin,NaN,NaN,NaN,n.,50.0,234,urchin,NaN,NaN,NaN
3284,4,debĭʹltāte,NaN,NaN,NaN,v.,21.0,65,debiltate,NaN,NaN,NaN
7807,2,līʹar,NaN,NaN,NaN,n.,73.0,129,liar,NaN,NaN,NaN
2672,3,cŏnfŏʹrmift,NaN,NaN,NaN,n.,51.0,56,conformift,NaN,NaN,NaN
12362,2,sĕʹnſes,NaN,NaN,NaN,n.,45.0,193,senses,NaN,NaN,NaN
10271,3,plĕʹnte_o_us,NaN,NaN,NaN,a.,30.0,164,plenteous,NaN,NaN,NaN
13515,3,sy̆ʹncŏpè,G.,NaN,NaN,n.,44.0,209,syoncope,NaN,NaN,NaN
6279,5,hiėrŏgly̆ʹphic,G.,NaN,NaN,a.,10.0,107,hieroglyophic,NaN,NaN,NaN
15563,1,whĭt,NaN,NaN,NaN,n.,17.0,238,whit,NaN,NaN,NaN
349,5,ăllĭgāʹtion,L.,NaN,NaN,n.,27.0,24,alligation,NaN,NaN,NaN
6880,3,iʹndĭan,NaN,NaN,NaN,n.,74.0,116,indian,NaN,NaN,NaN
6483,3,je_o_ʹpărdy,NaN,NaN,NaN,n.,38.0,111,jeopardy,NaN,NaN,NaN
2385,2,cŏckrel,NaN,nbSyll>1 et pas d'accent tonic,NaN,n.,51.0,52,cockrel,NaN,NaN,NaN
10083,3,phăʹntăſy,NaN,NaN,NaN,n.,58.0,161,phantasy,NaN,NaN,NaN
9777,3,păʹrtĭſan,NaN,NaN,NaN,n.,41.0,157,partisan,NaN,NaN,NaN
10854,2,pŭʹck_e_r,NaN,NaN,NaN,v.,37.0,172,pucker,NaN,NaN,NaN
4256,1,ĕgg,NaN,NaN,NaN,n.,64.0,78,egg,NaN,NaN,NaN
13626,2,tauʹrus,L.,NaN,NaN,n.,15.0,211,taurus,NaN,NaN,NaN
7928,1,load,NaN,NaN,NaN,n.,50.0,131,load,NaN,NaN,NaN

In [15]:
datej[datej['hwd'] =='castor']

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette,hwd,pronSampa,ipa
1936,2,caſtor,NaN,nbSyll>1 et pas d'accent tonic,NaN,n.,33.0,46,castor,castor,k { s t 3:r,kæstɜ:r

In [16]:
#bonus

In [17]:
#sauvegarde 
datej.to_csv("./../data/dataframe/BuchananRich.csv",sep=";",encoding="utf8",index=False)

In [18]:
#fait le bonus (notes papier)
#renommer variable et fonctions, fait des titres